"""Canonical parameter definitions for the dashboard.

Every entry describes a metric actually computed/displayed elsewhere in this
codebase. Definitions and formulas here must match the real implementation
(core/constellation_analytics.py, core/observation_duration.py,
core/cumulative_coverage.py, api.py) -- this module documents, it does not
recompute or reinterpret anything.
"""

GLOSSARY = [
    {
        "key": "coverage_percent",
        "name": "AOI Coverage %",
        "definition": "Share of the mission's AOI analysis grid (Australia or India, whichever this mission targets) that at least one satellite's sensor footprint has passed over during the simulation window.",
        "unit": "%",
        "source": "State Report (satellite ground track) + camera swath model",
        "calculation": "Covered grid cells / total AOI grid cells x 100, from core.cumulative_coverage.cumulative_region_coverage()",
        "significance": "Indicates how much of the target area has any observation opportunity at all; does not measure how often (see Revisit).",
    },
    {
        "key": "mean_revisit",
        "name": "Mean Revisit Time",
        "definition": "Average time interval between consecutive passes over a sampled AOI grid point, counting a pass by any satellite in the fleet -- this is a whole-constellation figure, not one craft's own revisit cycle. Every satellite's passes over that point are pooled into one shared timeline before the gaps between them are measured.",
        "unit": "minutes",
        "source": "State Report, densified ground track",
        "calculation": "Mean of per-cell time gaps between passes within sensor range, gaps pooled across all satellites per cell, from core.constellation_analytics.compute_revisit_analytics()",
        "significance": "Lower mean revisit means the constellation (as a fleet, whichever satellite happens to be overhead) can re-image a location sooner on average -- it is not a statement about how often any single satellite individually returns.",
    },
    {
        "key": "min_revisit",
        "name": "Minimum Revisit Time",
        "definition": "Shortest observed interval between two consecutive passes over the same AOI grid cell, where those two passes can be from two different satellites -- fleet-pooled, not per-satellite.",
        "unit": "minutes",
        "source": "State Report",
        "calculation": "Minimum of all per-cell pass-to-pass gaps, pooled across every satellite's passes over that cell",
        "significance": "Best-case re-observation latency achieved anywhere in the AOI by the fleet as a whole.",
    },
    {
        "key": "max_revisit",
        "name": "Maximum Revisit Time",
        "definition": "Longest observed interval between two consecutive passes over the same AOI grid cell (that had at least 2 real passes). Passes from every satellite in the fleet are pooled into that cell's shared timeline first -- this is the worst gap left anywhere in the AOI by the constellation as a whole, not the revisit cycle of any one satellite.",
        "unit": "minutes",
        "source": "State Report",
        "calculation": "Maximum of all per-cell pass-to-pass gaps, gaps pooled across every satellite's passes per cell, excluding cells with insufficient data",
        "significance": "Worst-case re-observation latency for the fleet; a large value flags a coverage weak spot the constellation as configured leaves exposed, regardless of which satellite would eventually reach it.",
    },
    {
        "key": "gap_largest",
        "name": "Largest Gap",
        "definition": "The single longest gap between consecutive passes across all AOI grid cells that had enough real samples to compute a gap -- fleet-pooled per cell, the same basis as Maximum Revisit Time, not a single satellite's own gap.",
        "unit": "minutes",
        "source": "Derived from the same per-cell pass data as revisit",
        "calculation": "max(avgRevisitMin, maxRevisitMin) across data-bearing cells only, from core.constellation_analytics.compute_gap_analysis()",
        "significance": "The most extreme observation blackout period found in the analysis grid, counting coverage by the constellation as a whole.",
    },
    {
        "key": "gap_mean",
        "name": "Mean Gap",
        "definition": "The average of one pooled list: every data-bearing AOI grid cell's average revisit time AND its own maximum revisit time, both values from every cell combined into one array.",
        "unit": "minutes",
        "source": "Same per-cell revisit data as Largest Gap",
        "calculation": "mean(avgRevisitMin, maxRevisitMin) across all data-bearing cells, from core.constellation_analytics.compute_gap_analysis()",
        "significance": "Not the same figure as \"Mean Revisit\" on the Revisit Analytics page, even though the two sound alike and are often close -- that one averages every individual pass-to-pass gap directly; this one averages a coarser two-numbers-per-cell summary (that cell's own average and its own worst gap). Comparing the two pages side by side can show genuinely different mean values for this reason, not a data error.",
    },
    {
        "key": "gap_median",
        "name": "Median Gap",
        "definition": "The midpoint of the same pooled list Mean Gap is averaged from: every data-bearing cell's average revisit time and its maximum revisit time, combined.",
        "unit": "minutes",
        "source": "Same per-cell revisit data as Largest Gap",
        "calculation": "median(avgRevisitMin, maxRevisitMin) across all data-bearing cells, from core.constellation_analytics.compute_gap_analysis()",
        "significance": "Half of that pooled list of cell-level average/maximum gaps falls below this value, half above -- less sensitive to one extreme outlier cell than Mean Gap.",
    },
    {
        "key": "gap_max",
        "name": "Maximum Gap",
        "definition": "The largest value in the same pooled cell-level list.",
        "unit": "minutes",
        "source": "Same per-cell revisit data as Largest Gap",
        "calculation": "max(avgRevisitMin, maxRevisitMin) across all data-bearing cells -- identical formula and identical result to Largest Gap on this same page (deliberately: both report the same worst-case figure, just placed differently in the layout).",
        "significance": "Shown alongside Largest Gap for layout/grouping reasons, not because they measure different things -- expect the two cards to always show the same number.",
    },
    {
        "key": "gap_p95",
        "name": "95th Percentile Gap",
        "definition": "The value below which 95% of the pooled cell-level list (every data-bearing cell's average AND maximum revisit time) falls.",
        "unit": "minutes",
        "source": "Same per-cell revisit data as Largest Gap",
        "calculation": "numpy 95th percentile of (avgRevisitMin, maxRevisitMin) across all data-bearing cells, from core.constellation_analytics.compute_gap_analysis()",
        "significance": "A near-worst-case figure that discounts the single most extreme cell -- useful when Maximum Gap is driven by one unusually sparse grid cell that would otherwise dominate the headline number.",
    },
    {
        "key": "gap_requirement_satisfied",
        "name": "Requirement Satisfied",
        "definition": "Share of data-bearing AOI grid cells whose own average revisit time meets the mission's stated revisit requirement.",
        "unit": "%",
        "source": "Mission revisit requirement (currently a fixed 60-minute default in every mission's own analysis) + per-cell average revisit time",
        "calculation": "count(cells where avgRevisitMin <= requirementMin) / count(data-bearing cells) x 100, from core.constellation_analytics.compute_gap_analysis()",
        "significance": "The fraction of the AOI actually meeting the SLA target on average, not a pass/fail for the whole mission -- a low percentage here means most of the AOI's revisit performance falls short of the stated requirement even though some cells meet it.",
    },
    {
        "key": "gap_distribution_chart",
        "name": "Temporal Gap Duration Breakdown",
        "definition": "Every data-bearing AOI grid cell, bucketed by its own average revisit time into one of four duration bands.",
        "unit": "n/a",
        "source": "Per-cell average revisit time (avgRevisitMin), same source as the KPI cards above",
        "calculation": "count(cells) grouped into < 30 min / 30-60 min / 1-2 hours / > 2 hours by avgRevisitMin, from core.constellation_analytics.compute_gap_analysis()",
        "significance": "Uses only each cell's average revisit time, not the average-plus-maximum pool the KPI cards above are computed from -- shows how many cells fall in each band rather than one summary statistic, so a mission dominated by a few very slow cells looks different here than in the Mean/Median KPI alone.",
    },
    {
        "key": "gap_insufficient_data",
        "name": "Insufficient Data (grid cell)",
        "definition": "A revisit/gap-analysis grid cell where fewer than 2 real satellite passes were recorded, so no gap could be computed.",
        "unit": "n/a",
        "source": "State Report sample density",
        "calculation": "Cell flagged insufficientData=true instead of being assigned a value; excluded from all aggregate gap/revisit statistics",
        "significance": "A high insufficient-data count (common for small constellations or short simulation windows) means the coverage-gap statistics for that area are not yet meaningful -- more simulated time or satellites are needed before drawing conclusions there.",
    },
    {
        "key": "contact_duration",
        "name": "Contact Duration",
        "definition": "Time during which a valid communication link exists between a spacecraft and a ground station.",
        "unit": "seconds",
        "source": "ground-contact report",
        "calculation": "Contact Stop Time - Contact Start Time, as reported directly per contact event",
        "significance": "Longer contacts allow more data downlink or command uplink per pass.",
    },
    {
        "key": "eclipse_duration",
        "name": "Eclipse Duration",
        "definition": "Time during which the spacecraft is inside Earth's shadow (Umbra or Penumbra).",
        "unit": "seconds",
        "source": "eclipse report",
        "calculation": "Eclipse Stop Time - Eclipse Start Time, as reported directly per eclipse event",
        "significance": "Affects power generation (solar panels can't charge) and imaging (no sunlit scene) during that period.",
    },
    {
        "key": "eclipse_type",
        "name": "Eclipse Type (Umbra / Penumbra)",
        "definition": "Umbra: the spacecraft is fully shadowed by Earth (no direct sunlight). Penumbra: the spacecraft is in Earth's partial shadow (some direct sunlight is blocked).",
        "unit": "n/a",
        "source": "eclipse report",
        "calculation": "Reported directly by the eclipse geometry calculation",
        "significance": "Umbra periods are the most power-constrained; Penumbra is a brief transition.",
    },
    {
        "key": "duty_cycle",
        "name": "Duty Cycle",
        "definition": "Percentage of a satellite's sampled timeline during which it is actively observing the AOI (sensor footprint intersecting the mission's target region).",
        "unit": "%",
        "source": "State Report + camera swath model",
        "calculation": "Active samples / total samples x 100, from api.py build_duty()",
        "significance": "Indicates how much of a satellite's orbit time is spent usefully observing the target area versus overflying elsewhere.",
    },
    {
        "key": "aoi",
        "name": "AOI (Area of Interest)",
        "definition": "The geographic region selected for mission analysis.",
        "unit": "n/a",
        "source": "Mission configuration (Mission_Configuration.xlsx)",
        "calculation": "A bounding polygon/rectangle -- mainland Australia + Tasmania for an Australia-targeted mission, or the equivalent India land boundary for an India-targeted mission -- used to filter/intersect satellite ground tracks",
        "significance": "All coverage, revisit, and observation-opportunity metrics are scoped to this region unless otherwise noted.",
    },
    {
        "key": "min_elevation",
        "name": "Minimum Elevation Angle",
        "definition": "Minimum spacecraft elevation above the ground-station horizon required for a valid contact.",
        "unit": "degrees",
        "source": "Mission configuration Ground_Stations sheet",
        "calculation": "Configured per ground station/link type in the ground-contact configuration (this mission: RF 5 deg, Optical 20 deg)",
        "significance": "A lower mask angle allows contact to begin/end earlier/later in a pass (longer contact windows, but through more atmosphere); a higher mask (as used for optical/laser links) avoids low-elevation atmospheric distortion at the cost of shorter windows.",
    },
    {
        "key": "orbital_plane",
        "name": "Orbital Plane",
        "definition": "A distinct orbital path/orientation around Earth, shared by every satellite launched into it.",
        "unit": "n/a",
        "source": "Mission configuration (Constellation sheet) / RAAN in the mission script",
        "calculation": "Satellites sharing the same Right Ascension of Ascending Node (RAAN) belong to the same plane",
        "significance": "More planes generally spread coverage more evenly in longitude; more satellites per plane increases along-track revisit within that plane.",
    },
    {
        "key": "raan",
        "name": "RAAN (Right Ascension of Ascending Node)",
        "definition": "The angle, measured eastward from a reference direction, to the point where the orbit crosses the equator heading north.",
        "unit": "degrees",
        "source": "mission script orbital elements",
        "calculation": "Fixed at epoch per satellite/plane in the mission script (e.g. 0/120/240 deg for the 3x1 mission's 3 planes)",
        "significance": "Determines the orbital plane's orientation in inertial space and, combined with inclination, where ground tracks fall.",
    },
    {
        "key": "observation_opportunity",
        "name": "Observation Opportunity",
        "definition": "A time interval during which the spacecraft and sensor satisfy the required conditions (footprint over the AOI) for observation.",
        "unit": "n/a (interval)",
        "source": "State Report + camera swath model",
        "calculation": "Contiguous stretches where the sensor footprint intersects the AOI, from core.observation_duration.observation_duration_analysis()",
        "significance": "Counts and durations of these windows are the basis for imaging planning and coverage statistics.",
    },
    {
        "key": "ground_track",
        "name": "Ground Track",
        "definition": "The path traced on Earth's surface directly beneath a satellite as it orbits.",
        "unit": "n/a",
        "source": "State Report (Latitude/Longitude per timestamp)",
        "calculation": "Plotted directly from the parsed state history",
        "significance": "Shows which regions a satellite actually overflies and when.",
    },
    {
        "key": "swath",
        "name": "Ground Swath",
        "definition": "The width of the strip of Earth's surface visible to the camera sensor at a given moment.",
        "unit": "km",
        "source": "Payload configuration + orbit altitude",
        "calculation": "Derived from sensor field of view and orbit altitude, core.camera_model.build_camera_model()",
        "significance": "A wider swath covers more ground per pass but at coarser resolution for a fixed sensor size.",
    },
    {
        "key": "gsd",
        "name": "GSD (Ground Sample Distance)",
        "definition": "The distance on the ground represented by one pixel in the captured image.",
        "unit": "m/pixel",
        "source": "Payload configuration + orbit altitude",
        "calculation": "Derived from sensor pixel pitch, focal length and orbit altitude",
        "significance": "Smaller GSD means finer spatial resolution (more detail per pixel).",
    },
    {
        "key": "satellite_contribution",
        "name": "Satellite Coverage Contribution",
        "definition": "The share of total observed AOI coverage attributable to one specific satellite.",
        "unit": "%",
        "source": "State Report",
        "calculation": "That satellite's observed AOI seconds / fleet total observed AOI seconds x 100",
        "significance": "Identifies which satellites do the most (or least) of the coverage work in the constellation.",
    },
    {
        "key": "orbital_period",
        "name": "Orbital Period",
        "definition": "The time for one satellite to complete a full revolution around Earth.",
        "unit": "minutes",
        "source": "Orbit altitude (Keplerian two-body calculation)",
        "calculation": "T = 2*pi*sqrt(a^3 / mu), a = Earth radius + altitude, mu = Earth's gravitational parameter",
        "significance": "Shorter periods (lower altitude) generally mean more passes per day over a given target.",
    },
    {
        "key": "image_quality_score",
        "name": "Image Quality Score",
        "definition": "A derived 0-100 indicator of how usable an observation is, combining cloud obstruction, source-data completeness, sharpness, dynamic-range use and saturation.",
        "unit": "0-100",
        "source": "Derived from the generated product",
        "calculation": "Weighted mean of six factors (dataComplete 25%, cloudFree 20%, sharpness 20%, dynamicRange 15%, unsaturated 10%, notUnderexposed 10%), from core.quality.assess_quality()",
        "significance": "A single screening number for triaging which acquisitions are worth analysing. Every contributing factor is shown alongside it, so it is never a black box.",
    },
    {
        "key": "cloud_cover_percent",
        "name": "Cloud Cover %",
        "definition": "Share of the observation footprint estimated to be obscured by cloud.",
        "unit": "%",
        "source": "Sentinel-2 scene classification layer where available, otherwise a spectral test on the imagery",
        "calculation": "SCL cloud/shadow/cirrus classes, or a brightness-plus-spectral-flatness test; the method used is always reported with the value",
        "significance": "Cloud is the main reason an optical acquisition is unusable. The spectral fallback can over-report over bright arid ground, which matters for any mission's AOI with arid or desert terrain (e.g. the Australian outback or Rajasthan).",
    },
    {
        "key": "usable_image_percent",
        "name": "Usable Image %",
        "definition": "Share of the frame backed by real source imagery rather than left empty.",
        "unit": "%",
        "source": "Mosaic coverage of the footprint",
        "calculation": "Valid pixels / total pixels x 100. Gaps are never filled with invented ground; they are reported here and rendered as flat neutral.",
        "significance": "A footprint straddling a source-granule boundary may not fill completely. This states how much of the product is a real observation.",
    },
    {
        "key": "estimated_ground_resolution",
        "name": "Estimated Ground Resolution",
        "definition": "Ground distance represented by one pixel of the delivered product.",
        "unit": "m/pixel",
        "source": "Camera model + delivered raster size",
        "calculation": "Swath width / delivered pixel width. Coarser than the native instrument GSD whenever the delivered raster is capped below full sensor resolution.",
        "significance": "Sets what can actually be resolved in the delivered image, as opposed to what the instrument could resolve at full size.",
    },
    {
        "key": "observation_geometry",
        "name": "Observation Geometry",
        "definition": "How the sensor was pointed relative to the ground at acquisition: nadir (straight down) or off-nadir by some angle.",
        "unit": "degrees from nadir",
        "source": "state history + camera pointing configuration",
        "calculation": "Camera heading from the ground track; pointing mode from the payload configuration",
        "significance": "Off-nadir views cover more ground per pass but at coarser effective resolution and through more atmosphere.",
    },
    {
        "key": "simulated_atmosphere",
        "name": "Simulated Atmosphere",
        "definition": "A modelled atmospheric path added between the ground and the sensor: wavelength-dependent scattering plus transmission loss.",
        "unit": "reflectance",
        "source": "SIMULATED - not a measurement",
        "calculation": "toa = surface x transmittance + path radiance, Rayleigh-shaped (strongest in blue, negligible in near infrared), scaled by air mass for off-nadir views",
        "significance": "The source imagery is surface reflectance with the atmosphere removed, but a real payload observes top-of-atmosphere. This stage approximates what the sensor would actually record, and is always labelled as simulated.",
    },
    {
        "key": "mission_elapsed_time",
        "name": "Mission Elapsed Time (MET)",
        "definition": "Time elapsed since the start of the simulated mission timeline (first state-report epoch).",
        "unit": "DDD:HH:MM:SS",
        "source": "State Report",
        "calculation": "Timestamp - mission start timestamp",
        "significance": "Used to reference events on a mission-relative clock instead of absolute UTC.",
    },
    {
        "key": "median_revisit",
        "name": "Median Revisit Time (P50)",
        "definition": "The middle value of every pass-to-pass gap pooled from all sampled AOI grid points, counting a pass by any satellite in the fleet -- a whole-constellation figure, not any one craft's own revisit cycle. Half of all revisit intervals are shorter than this, half are longer.",
        "unit": "minutes",
        "source": "State Report, densified ground track",
        "calculation": "50th percentile of the pooled per-cell time gaps, from core.constellation_analytics.compute_revisit_analytics()",
        "significance": "Less skewed by a few extreme outliers than the mean -- a better read on the 'typical' revisit gap a location actually experiences.",
    },
    {
        "key": "p95_revisit",
        "name": "95th Percentile Revisit Time (P95)",
        "definition": "The gap length that 95% of all pooled revisit intervals fall below -- only the worst 5% of gaps are longer than this. Pooled across every satellite in the fleet per grid cell, not a per-satellite figure.",
        "unit": "minutes",
        "source": "State Report, densified ground track",
        "calculation": "95th percentile of the pooled per-cell time gaps, from core.constellation_analytics.compute_revisit_analytics()",
        "significance": "Characterises the long tail without being dominated by the single absolute worst case (Maximum Revisit Time) -- useful for setting a realistic worst-case SLA.",
    },
    {
        "key": "revisit_distribution",
        "name": "Revisit Time Frequency Distribution",
        "definition": "A histogram of every pass-to-pass gap pooled from all 180 sampled AOI grid points, grouped into 8 equal-width time bins from the shortest gap observed to the longest.",
        "unit": "count of intervals per bin",
        "source": "State Report, densified ground track",
        "calculation": "numpy.histogram(pooled gaps, bins=8), from core.constellation_analytics.compute_revisit_analytics()",
        "significance": "Where the Mean/Median/Best/Worst KPIs each collapse the whole distribution to one number, this chart shows its actual shape -- e.g. whether most of the AOI is revisited quickly with only a thin tail of slow cells, or whether long gaps are common. A tall left bar with a long low tail (the usual shape for a single Walker-Delta shell) means most locations are revisited quickly and only a few edge-of-swath cells wait much longer -- exactly the cells the Maximum/P95 KPIs are describing.",
    },
    {
        "key": "nominal_orbit_altitude",
        "name": "Nominal Orbit Altitude",
        "definition": "The constellation's design/configured circular orbit altitude -- a single fixed value, the same for every satellite regardless of where each one currently is in its orbit.",
        "unit": "km",
        "source": "Mission_Configuration.xlsx (Orbit table)",
        "calculation": "Read directly from the configuration file, not derived or propagated.",
        "significance": "The reference altitude the constellation is designed to fly at. Compare against Instantaneous Geodetic Altitude to see how far a satellite's real, propagated position deviates from this design value at any given moment.",
    },
    {
        "key": "instantaneous_geodetic_altitude",
        "name": "Instantaneous Geodetic Altitude",
        "definition": "A satellite's actual height above the reference ellipsoid at one specific moment in its propagated orbit. Unlike the fixed Nominal Orbit Altitude, this value changes continuously as the satellite moves, because a real orbit is never a perfect circle.",
        "unit": "km",
        "source": "State Report (Satellite_State_History.xlsx, 'Altitude' column)",
        "calculation": "Read per timestep from the propagated state. Where a min/mean/max is shown, it is this same quantity aggregated over the analysis window or over the fleet.",
        "significance": "Shows the real, physical deviation from the nominal design altitude. A wide spread between min and max, or a mean that drifts from the Nominal Orbit Altitude, signals orbital decay or drift that would need a correction.",
    },
    {
        "key": "footprint_alignment",
        "name": "Footprint Alignment",
        "definition": "Whether the simulated observation and the real Earth reference image cover the exact same ground area, in the same orientation and scale.",
        "unit": "pass/fail",
        "source": "core.products.generate_product",
        "calculation": "Both images are rendered from one identical windowed read (same bbox, same output raster shape) of the real Sentinel-2 mosaic -- alignment is guaranteed by that construction, not independently measured or registered.",
        "significance": "Confirms there is no separate registration step that could silently misalign the two images -- they are geometrically the same frame by design.",
    },
    {
        "key": "land_cover_similarity",
        "name": "Land-Cover Similarity",
        "definition": "How closely the simulated product's land-cover mix (water / vegetation / bare / urban / cloud) matches the real reference scene's, after the same spectral-index classifier is applied to both.",
        "unit": "%",
        "source": "core.validation.compare_scenes, using core.classify.classify_scene on both images",
        "calculation": "100 - (sum of |reference% - simulated%| across classes) / 2. The simulated side is classified on DN rescaled to a comparable range, not on the raw reflectance the reference uses.",
        "significance": "A high value means the sensor simulation (blur, noise, atmosphere) preserved the scene's real land-cover mix; a lower value quantifies how much those effects shifted the apparent scene -- expected to some degree, since the whole point of the simulation is to model a real sensor's imperfections, not reproduce the reference pixel-for-pixel.",
    },
    {
        "key": "validation_confidence",
        "name": "Overall Validation Confidence",
        "definition": "A single disclosed indicator combining coordinate validity, footprint alignment, land-cover similarity and image quality into one number.",
        "unit": "0-100",
        "source": "core.validation.compare_scenes",
        "calculation": "Weighted mean of the four factors (20% coordinate validity, 20% footprint alignment, 30% land-cover similarity, 30% image quality), itemised the same way the Quality Score is.",
        "significance": "SIMULATED indicator, not a measured scientific result and not a statement about ASC_074's real-world imaging performance -- it summarises the checks already shown individually, for a quick read, not a new measurement.",
    },
    {
        "key": "solar_elevation",
        "name": "Sun Elevation",
        "definition": "The angle of the sun above the horizon at the observation's location and simulated capture time.",
        "unit": "degrees",
        "source": "core.solar.solar_position",
        "calculation": "Standard low-precision solar position formula (Cooper's equation for declination, longitude-based local solar time, then the elevation identity) from the capture timestamp and sub-satellite latitude/longitude. No equation-of-time or refraction correction, accurate to roughly +/-2 degrees.",
        "significance": "Characterises illumination conditions -- low or negative sun elevation means long shadows, a dim scene, or a night-side capture, none of which the sensor simulation currently adjusts pixel rendering for.",
    },
    {
        "key": "spectral_band_proxy",
        "name": "Spectral Band Proxy",
        "definition": "The center wavelength and bandwidth shown for each band (Red/Green/Blue/Near Infrared) are Sentinel-2's own published MSI specification, not a specification of ASC_074's own sensor.",
        "unit": "nm",
        "source": "core.spectral.SPECTRAL_BANDS",
        "calculation": "ASC_074's spectral response has never been specified in any mission file -- only the band names exist. The pipeline reads real Sentinel-2 L2A pixel data for each named band (Blue->B02, Green->B03, Red->B04, Near Infrared->B08), so Sentinel-2's real, published wavelength and bandwidth numbers are reported here as an ASSUMED proxy describing what data is actually feeding the pipeline.",
        "significance": "Makes explicit that using this data does not demonstrate ASC_074 has an identical spectral response to Sentinel-2 -- only that its simulated bands are currently modelled as if it did.",
    },
    {
        "key": "ground_swath",
        "name": "Ground Swath",
        "definition": "The cross-track width of ground the pushbroom sensor images in a single pass, at the mission's nominal orbit altitude.",
        "unit": "km",
        "source": "core.camera_model.build_camera_model, from the mission's payload geometry (real Excel config values where present, documented defaults otherwise)",
        "calculation": "Horizontal field of view HFOV = 2 x atan(Sensor Width / (2 x Focal Length)); Ground Swath = 2 x Altitude x tan(HFOV / 2). GSD (m/pixel) = Swath x 1000 / Image Width (px), shown alongside it.",
        "significance": "A fixed geometric property of the camera + orbit, shared by every satellite in the fleet -- calculated from lens/sensor/altitude numbers, not measured from any actual image. It sets the width of every strip the fleet can capture, and directly sizes the other three cards on this page.",
    },
    {
        "key": "estimated_scenes_captured",
        "name": "Estimated Scenes Captured",
        "definition": "How many discrete 'scenes' the fleet's continuous imaging strips would divide into, if that strip were cut into frames the size of a nominal along-track frame footprint -- a pushbroom sensor doesn't actually take discrete photos, so this is an estimate for reporting purposes, not a raw payload counter.",
        "unit": "scenes",
        "source": "core.imaging_summary.build_imaging_summary, using each satellite's median ground-track speed and its total observation seconds from the per-satellite observation-duration report",
        "calculation": "Per satellite: Imaged Distance (km) / Frame Footprint (km), where Frame Footprint = GSD (m/pixel) x Image Height (px) / 1000. Fleet total is the sum of every satellite's estimated scene count over the loaded analysis window.",
        "significance": "Frame Footprint uses the camera's fixed nominal Image Height constant, not any single generated product's actual delivered size -- this card estimates a fleet-wide count for the loaded time window, and scales up proportionally for a longer simulation run.",
    },
    {
        "key": "imaged_distance",
        "name": "Imaged Distance",
        "definition": "The total along-track ground distance the fleet's sensors swept while actively observing the AOI, summed across every satellite.",
        "unit": "km",
        "source": "core.imaging_summary.build_imaging_summary, from State Report ground-track fixes and per-satellite Total Observation Seconds",
        "calculation": "Per satellite: median ground-track speed (km/s, from consecutive State Report fixes via the haversine distance formula) x that satellite's Total Observation Seconds. Fleet total sums this across all satellites.",
        "significance": "The length of ground track actually swept during observation, not the satellite's full orbital path -- longer or shorter simulation runs change this proportionally, and it is the basis for both Estimated Scenes Captured and Imaged Area below.",
    },
    {
        "key": "imaged_area_fleet_effort",
        "name": "Imaged Area (Fleet-Effort)",
        "definition": "Total ground area swept by the fleet's sensor footprints while observing the AOI, summed per satellite.",
        "unit": "km²",
        "source": "core.imaging_summary.build_imaging_summary",
        "calculation": "Per satellite: Imaged Distance (km) x Ground Swath (km). Fleet total sums this across all satellites.",
        "significance": "A summed per-satellite effort figure, not a unique-area figure -- if two satellites image the same ground twice, both passes are counted, so this can exceed the AOI's actual land area. It measures total sensor effort spent, not distinct area covered (see AOI Coverage % for that).",
    },
    {
        "key": "constellation_name",
        "name": "Constellation Name",
        "definition": "The mission name as configured for this run.",
        "unit": "n/a",
        "source": "Mission_Configuration.xlsx (Mission table, \"Mission Name\")",
        "calculation": "Read directly from the configuration file -- not derived, not calculated.",
        "significance": "Identifies which mission configuration produced every other figure on this page.",
    },
    {
        "key": "constellation_configuration",
        "name": "Configuration (Planes x Sats/Plane)",
        "definition": "The Walker-Delta shell shape: how many orbital planes the fleet is split across, and how many satellites sit in each plane.",
        "unit": "n/a",
        "source": "Mission_Configuration.xlsx (Constellation table, \"Number of Planes\" x \"Satellites per Plane\")",
        "calculation": "Read directly from the configuration file and formatted as \"planes × satellites per plane\" -- not derived.",
        "significance": "Sets the fleet's geometry: more planes spread coverage across more ground tracks at once, while more satellites per plane shortens the gap between consecutive passes on any one track.",
    },
    {
        "key": "total_satellites_configured",
        "name": "Total Satellites (Configured)",
        "definition": "The fleet size this mission is configured to fly -- planes x satellites per plane.",
        "unit": "satellites",
        "source": "Mission_Configuration.xlsx (Constellation table, \"Total Satellites\")",
        "calculation": "Read directly from the configuration file, not derived or counted from telemetry (see Operational Satellites for the telemetry-detected count).",
        "significance": "The design fleet size every other per-fleet figure on this page (Ground Tracks/Day, Images/Day, etc.) scales against.",
    },
    {
        "key": "operational_satellites",
        "name": "Operational Satellites",
        "definition": "The number of distinct satellites that actually appear in this run's own State Report telemetry -- a telemetry-detected count, not a health or activation status.",
        "unit": "satellites",
        "source": "State Report (\"Satellite Name\" column)",
        "calculation": "Count of distinct Satellite Name values present in the state telemetry file. If the state file is empty or unavailable, this falls back to the configured Total Satellites count rather than showing zero.",
        "significance": "In every mission run seen so far this equals the configured fleet size (every configured satellite has telemetry) -- so it functions as a telemetry-completeness check more than a live operations status. The \"100% Active\" badge shown alongside it is a fixed label, not a separately computed percentage; it is not recalculated if the detected count ever falls short of the configured count.",
    },
    {
        "key": "inclination_deg",
        "name": "Inclination",
        "definition": "The orbital plane's tilt relative to Earth's equator.",
        "unit": "degrees",
        "source": "Mission_Configuration.xlsx (Orbit table, \"Inclination\")",
        "calculation": "Read directly from the configuration file, not derived.",
        "significance": "Sets which latitudes the constellation ever passes over (an inclination of I degrees reaches roughly ±I degrees of latitude). Whether the orbit is sun-synchronous is NOT determined by inclination alone -- see Orbit Type, which checks inclination together with altitude via the real J2 nodal-precession rate, not an inclination-range guess.",
    },
    {
        "key": "global_coverage_duty_cycle",
        "name": "Global Coverage",
        "definition": "Despite the label, this card does not show a land-area coverage percentage (that figure is AOI Coverage %, shown elsewhere). It reuses the Overall Observation Duty Cycle value: the share of the fleet's sampled timeline during which at least one satellite's sensor footprint is over the AOI.",
        "unit": "%",
        "source": "api.py build_duty() (\"Overall Observation Duty Cycle (%)\"), same figure as the Observation Duty KPI on the Coverage Map page",
        "calculation": "Active AOI-observing samples / total samples x 100, across the fleet -- a time-based figure, not a spatial land-cell count.",
        "significance": "This card's label (\"Global Coverage\") and subtitle (\"Accumulated land surface vision\") describe a spatial coverage metric, but the number shown is the same time-based Duty Cycle statistic used elsewhere in the app under that name -- worth knowing if comparing this figure against AOI Coverage % (core.cumulative_coverage), which is a genuinely different, grid-cell-based calculation.",
    },
    {
        "key": "images_per_day",
        "name": "Images / Day",
        "definition": "The fleet's total Estimated Scenes Captured, expressed as a rate per day rather than a total over the loaded analysis window.",
        "unit": "scenes/day",
        "source": "core.imaging_summary.build_imaging_summary (scene count) + State Report timestamp span (days)",
        "calculation": "Total Estimated Scenes (see the Payload & Imaging page's own KPI of the same figure) / number of real days spanned by the loaded State Report timestamps (minimum 1 day).",
        "significance": "A per-day rate is only as meaningful as the window it was computed over -- a short simulation run still divides by at least 1 day, so a partial day's data is not artificially inflated into a full day's rate, but very short runs will understate the true daily rate.",
    },
    {
        "key": "rf_contacts_per_day",
        "name": "RF Contacts / Day",
        "definition": "How many real RF ground-station contact events were recorded, expressed as a rate per day.",
        "unit": "contacts/day",
        "source": "RF ground-contact report",
        "calculation": "Count of RF contact rows / number of real days spanned by the loaded State Report timestamps (minimum 1 day).",
        "significance": "Downlink/uplink opportunity frequency -- higher means more frequent windows to command the fleet or retrieve data, but says nothing about each window's length (see Avg Contact Duration).",
    },
    {
        "key": "ground_tracks_per_day",
        "name": "Ground Tracks / Day",
        "definition": "How many times the whole fleet crosses the globe (pole-to-pole) in 24 hours, combined across every operational satellite.",
        "unit": "tracks/day",
        "source": "core.constellation_analytics.compute_constellation_summary, from Orbital Period and Operational Satellites",
        "calculation": "(1440 / Orbital Period in minutes) x Operational Satellites -- one satellite's revolutions per day, multiplied by the fleet size actually detected in telemetry.",
        "significance": "A fleet-wide transit count, not a per-satellite figure -- it scales with both a shorter orbital period (lower altitude) and a larger operational fleet.",
    },
    {
        "key": "avg_contact_duration",
        "name": "Avg Contact Duration",
        "definition": "The mean length of every real RF ground-station contact recorded in this run, not one specific pass.",
        "unit": "minutes",
        "source": "RF ground-contact report (\"Duration (s)\" column)",
        "calculation": "Sum of every RF contact's Duration (s), divided by the number of RF contacts, converted to minutes.",
        "significance": "A single average across every contact and every ground station in the run -- individual passes vary with elevation angle and geometry (see Contact Duration for the per-event figure this is averaged from).",
    },
    {
        "key": "samples_per_satellite",
        "name": "Samples",
        "definition": "How many state-telemetry rows exist for this satellite in the loaded window -- not a count of anything unique to it.",
        "unit": "rows",
        "source": "State Report (Satellite_State_History.xlsx)",
        "calculation": "Count of rows for this satellite's Timestamp column.",
        "significance": "Identical for every satellite in the fleet by construction, not a coincidence or a bug: the raw report puts every satellite's state on one shared UTC time grid -- one row per timestamp, all satellites' fields as columns on that same row -- so each is observed exactly as many times as there are rows in the window. Kept as a data-quality check: if any satellite ever showed a different count, that would mean its own telemetry had missing or unparseable rows for part of the window.",
    },
]

BY_KEY = {item["key"]: item for item in GLOSSARY}
