"""Canonical parameter definitions for the dashboard.

Every entry describes a metric actually computed/displayed elsewhere in this
codebase. Definitions and formulas here must match the real implementation
(core/constellation_analytics.py, core/observation_duration.py,
core/cumulative_coverage.py, api.py) -- this module documents, it does not
recompute or reinterpret anything.
"""

GLOSSARY = [
    {
        "key": "coverage_percent",
        "name": "Australia Coverage %",
        "definition": "Share of the Australia analysis grid that at least one satellite's sensor footprint has passed over during the simulation window.",
        "unit": "%",
        "source": "GMAT State Report (satellite ground track) + camera swath model",
        "calculation": "Covered grid cells / total AOI grid cells x 100, from core.cumulative_coverage.cumulative_australia_coverage()",
        "significance": "Indicates how much of the target area has any observation opportunity at all; does not measure how often (see Revisit).",
    },
    {
        "key": "mean_revisit",
        "name": "Mean Revisit Time",
        "definition": "Average time interval between consecutive valid observation opportunities for a sampled AOI grid point.",
        "unit": "minutes",
        "source": "GMAT State Report, densified ground track",
        "calculation": "Mean of per-cell time gaps between passes within sensor range, from core.constellation_analytics.compute_revisit_analytics()",
        "significance": "Lower mean revisit means the constellation can re-image a location sooner on average.",
    },
    {
        "key": "min_revisit",
        "name": "Minimum Revisit Time",
        "definition": "Shortest observed interval between two consecutive passes over the same AOI grid cell.",
        "unit": "minutes",
        "source": "GMAT State Report",
        "calculation": "Minimum of all per-cell pass-to-pass gaps",
        "significance": "Best-case re-observation latency achieved anywhere in the AOI.",
    },
    {
        "key": "max_revisit",
        "name": "Maximum Revisit Time",
        "definition": "Longest observed interval between two consecutive passes over the same AOI grid cell (that had at least 2 real passes).",
        "unit": "minutes",
        "source": "GMAT State Report",
        "calculation": "Maximum of all per-cell pass-to-pass gaps, excluding cells with insufficient data",
        "significance": "Worst-case re-observation latency; a large value flags a coverage weak spot.",
    },
    {
        "key": "gap_largest",
        "name": "Largest Gap",
        "definition": "The single longest gap between consecutive passes across all AOI grid cells that had enough real samples to compute a gap.",
        "unit": "minutes",
        "source": "Derived from the same per-cell pass data as revisit",
        "calculation": "max(avgRevisitMin, maxRevisitMin) across data-bearing cells only, from core.constellation_analytics.compute_gap_analysis()",
        "significance": "The most extreme observation blackout period found in the analysis grid.",
    },
    {
        "key": "gap_insufficient_data",
        "name": "Insufficient Data (grid cell)",
        "definition": "A revisit/gap-analysis grid cell where fewer than 2 real satellite passes were recorded, so no gap could be computed.",
        "unit": "n/a",
        "source": "GMAT State Report sample density",
        "calculation": "Cell flagged insufficientData=true instead of being assigned a value; excluded from all aggregate gap/revisit statistics",
        "significance": "A high insufficient-data count (common for small constellations or short simulation windows) means the coverage-gap statistics for that area are not yet meaningful -- more simulated time or satellites are needed before drawing conclusions there.",
    },
    {
        "key": "contact_duration",
        "name": "Contact Duration",
        "definition": "Time during which a valid communication link exists between a spacecraft and a ground station.",
        "unit": "seconds",
        "source": "GMAT Contact Locator report",
        "calculation": "Contact Stop Time - Contact Start Time, as reported directly by GMAT per contact event",
        "significance": "Longer contacts allow more data downlink or command uplink per pass.",
    },
    {
        "key": "eclipse_duration",
        "name": "Eclipse Duration",
        "definition": "Time during which the spacecraft is inside Earth's shadow (Umbra or Penumbra).",
        "unit": "seconds",
        "source": "GMAT Eclipse Locator report",
        "calculation": "Eclipse Stop Time - Eclipse Start Time, as reported directly by GMAT per eclipse event",
        "significance": "Affects power generation (solar panels can't charge) and imaging (no sunlit scene) during that period.",
    },
    {
        "key": "eclipse_type",
        "name": "Eclipse Type (Umbra / Penumbra)",
        "definition": "Umbra: the spacecraft is fully shadowed by Earth (no direct sunlight). Penumbra: the spacecraft is in Earth's partial shadow (some direct sunlight is blocked).",
        "unit": "n/a",
        "source": "GMAT Eclipse Locator report",
        "calculation": "Reported directly by GMAT's eclipse geometry calculation",
        "significance": "Umbra periods are the most power-constrained; Penumbra is a brief transition.",
    },
    {
        "key": "duty_cycle",
        "name": "Duty Cycle",
        "definition": "Percentage of a satellite's sampled timeline during which it is actively observing the AOI (sensor footprint intersecting Australia).",
        "unit": "%",
        "source": "GMAT State Report + camera swath model",
        "calculation": "Active samples / total samples x 100, from api.py build_duty()",
        "significance": "Indicates how much of a satellite's orbit time is spent usefully observing the target area versus overflying elsewhere.",
    },
    {
        "key": "aoi",
        "name": "AOI (Area of Interest)",
        "definition": "The geographic region selected for mission analysis.",
        "unit": "n/a",
        "source": "Mission configuration (Mission_Configuration.xlsx)",
        "calculation": "A bounding polygon/rectangle (mainland Australia + Tasmania outline for this mission) used to filter/intersect satellite ground tracks",
        "significance": "All coverage, revisit, and observation-opportunity metrics are scoped to this region unless otherwise noted.",
    },
    {
        "key": "min_elevation",
        "name": "Minimum Elevation Angle",
        "definition": "Minimum spacecraft elevation above the ground-station horizon required for a valid contact.",
        "unit": "degrees",
        "source": "Mission configuration Ground_Stations sheet",
        "calculation": "Configured per ground station/link type in GMAT's Contact Locator (this mission: RF 5 deg, Optical 20 deg)",
        "significance": "A lower mask angle allows contact to begin/end earlier/later in a pass (longer contact windows, but through more atmosphere); a higher mask (as used for optical/laser links) avoids low-elevation atmospheric distortion at the cost of shorter windows.",
    },
    {
        "key": "orbital_plane",
        "name": "Orbital Plane",
        "definition": "A distinct orbital path/orientation around Earth, shared by every satellite launched into it.",
        "unit": "n/a",
        "source": "Mission configuration (Constellation sheet) / RAAN in the GMAT script",
        "calculation": "Satellites sharing the same Right Ascension of Ascending Node (RAAN) belong to the same plane",
        "significance": "More planes generally spread coverage more evenly in longitude; more satellites per plane increases along-track revisit within that plane.",
    },
    {
        "key": "raan",
        "name": "RAAN (Right Ascension of Ascending Node)",
        "definition": "The angle, measured eastward from a reference direction, to the point where the orbit crosses the equator heading north.",
        "unit": "degrees",
        "source": "GMAT script orbital elements",
        "calculation": "Fixed at epoch per satellite/plane in the GMAT script (e.g. 0/120/240 deg for the 3x1 mission's 3 planes)",
        "significance": "Determines the orbital plane's orientation in inertial space and, combined with inclination, where ground tracks fall.",
    },
    {
        "key": "observation_opportunity",
        "name": "Observation Opportunity",
        "definition": "A time interval during which the spacecraft and sensor satisfy the required conditions (footprint over the AOI) for observation.",
        "unit": "n/a (interval)",
        "source": "GMAT State Report + camera swath model",
        "calculation": "Contiguous stretches where the sensor footprint intersects the AOI, from core.observation_duration.observation_duration_analysis()",
        "significance": "Counts and durations of these windows are the basis for imaging planning and coverage statistics.",
    },
    {
        "key": "ground_track",
        "name": "Ground Track",
        "definition": "The path traced on Earth's surface directly beneath a satellite as it orbits.",
        "unit": "n/a",
        "source": "GMAT State Report (Latitude/Longitude per timestamp)",
        "calculation": "Plotted directly from the parsed state history",
        "significance": "Shows which regions a satellite actually overflies and when.",
    },
    {
        "key": "swath",
        "name": "Ground Swath",
        "definition": "The width of the strip of Earth's surface visible to the camera sensor at a given moment.",
        "unit": "km",
        "source": "Payload configuration + orbit altitude",
        "calculation": "Derived from sensor field of view and orbit altitude, core.camera_model.build_camera_model()",
        "significance": "A wider swath covers more ground per pass but at coarser resolution for a fixed sensor size.",
    },
    {
        "key": "gsd",
        "name": "GSD (Ground Sample Distance)",
        "definition": "The distance on the ground represented by one pixel in the captured image.",
        "unit": "m/pixel",
        "source": "Payload configuration + orbit altitude",
        "calculation": "Derived from sensor pixel pitch, focal length and orbit altitude",
        "significance": "Smaller GSD means finer spatial resolution (more detail per pixel).",
    },
    {
        "key": "satellite_contribution",
        "name": "Satellite Coverage Contribution",
        "definition": "The share of total observed AOI coverage attributable to one specific satellite.",
        "unit": "%",
        "source": "GMAT State Report",
        "calculation": "That satellite's observed AOI seconds / fleet total observed AOI seconds x 100",
        "significance": "Identifies which satellites do the most (or least) of the coverage work in the constellation.",
    },
    {
        "key": "orbital_period",
        "name": "Orbital Period",
        "definition": "The time for one satellite to complete a full revolution around Earth.",
        "unit": "minutes",
        "source": "Orbit altitude (Keplerian two-body calculation)",
        "calculation": "T = 2*pi*sqrt(a^3 / mu), a = Earth radius + altitude, mu = Earth's gravitational parameter",
        "significance": "Shorter periods (lower altitude) generally mean more passes per day over a given target.",
    },
    {
        "key": "image_quality_score",
        "name": "Image Quality Score",
        "definition": "A derived 0-100 indicator of how usable an observation is, combining cloud obstruction, source-data completeness, sharpness, dynamic-range use and saturation.",
        "unit": "0-100",
        "source": "Derived from the generated product",
        "calculation": "Weighted mean of six factors (dataComplete 25%, cloudFree 20%, sharpness 20%, dynamicRange 15%, unsaturated 10%, notUnderexposed 10%), from core.quality.assess_quality()",
        "significance": "A single screening number for triaging which acquisitions are worth analysing. Every contributing factor is shown alongside it, so it is never a black box.",
    },
    {
        "key": "cloud_cover_percent",
        "name": "Cloud Cover %",
        "definition": "Share of the observation footprint estimated to be obscured by cloud.",
        "unit": "%",
        "source": "Sentinel-2 scene classification layer where available, otherwise a spectral test on the imagery",
        "calculation": "SCL cloud/shadow/cirrus classes, or a brightness-plus-spectral-flatness test; the method used is always reported with the value",
        "significance": "Cloud is the main reason an optical acquisition is unusable. The spectral fallback can over-report over bright arid ground, which matters over Australia.",
    },
    {
        "key": "usable_image_percent",
        "name": "Usable Image %",
        "definition": "Share of the frame backed by real source imagery rather than left empty.",
        "unit": "%",
        "source": "Mosaic coverage of the footprint",
        "calculation": "Valid pixels / total pixels x 100. Gaps are never filled with invented ground; they are reported here and rendered as flat neutral.",
        "significance": "A footprint straddling a source-granule boundary may not fill completely. This states how much of the product is a real observation.",
    },
    {
        "key": "estimated_ground_resolution",
        "name": "Estimated Ground Resolution",
        "definition": "Ground distance represented by one pixel of the delivered product.",
        "unit": "m/pixel",
        "source": "Camera model + delivered raster size",
        "calculation": "Swath width / delivered pixel width. Coarser than the native instrument GSD whenever the delivered raster is capped below full sensor resolution.",
        "significance": "Sets what can actually be resolved in the delivered image, as opposed to what the instrument could resolve at full size.",
    },
    {
        "key": "observation_geometry",
        "name": "Observation Geometry",
        "definition": "How the sensor was pointed relative to the ground at acquisition: nadir (straight down) or off-nadir by some angle.",
        "unit": "degrees from nadir",
        "source": "GMAT state history + camera pointing configuration",
        "calculation": "Camera heading from the ground track; pointing mode from the payload configuration",
        "significance": "Off-nadir views cover more ground per pass but at coarser effective resolution and through more atmosphere.",
    },
    {
        "key": "simulated_atmosphere",
        "name": "Simulated Atmosphere",
        "definition": "A modelled atmospheric path added between the ground and the sensor: wavelength-dependent scattering plus transmission loss.",
        "unit": "reflectance",
        "source": "SIMULATED - not a measurement",
        "calculation": "toa = surface x transmittance + path radiance, Rayleigh-shaped (strongest in blue, negligible in near infrared), scaled by air mass for off-nadir views",
        "significance": "The source imagery is surface reflectance with the atmosphere removed, but a real payload observes top-of-atmosphere. This stage approximates what the sensor would actually record, and is always labelled as simulated.",
    },
    {
        "key": "mission_elapsed_time",
        "name": "Mission Elapsed Time (MET)",
        "definition": "Time elapsed since the start of the simulated mission timeline (first state-report epoch).",
        "unit": "DDD:HH:MM:SS",
        "source": "GMAT State Report",
        "calculation": "Timestamp - mission start timestamp",
        "significance": "Used to reference events on a mission-relative clock instead of absolute UTC.",
    },
    {
        "key": "median_revisit",
        "name": "Median Revisit Time (P50)",
        "definition": "The middle value of every pass-to-pass gap pooled from all sampled AOI grid points -- half of all revisit intervals are shorter than this, half are longer.",
        "unit": "minutes",
        "source": "GMAT State Report, densified ground track",
        "calculation": "50th percentile of the pooled per-cell time gaps, from core.constellation_analytics.compute_revisit_analytics()",
        "significance": "Less skewed by a few extreme outliers than the mean -- a better read on the 'typical' revisit gap a location actually experiences.",
    },
    {
        "key": "p95_revisit",
        "name": "95th Percentile Revisit Time (P95)",
        "definition": "The gap length that 95% of all pooled revisit intervals fall below -- only the worst 5% of gaps are longer than this.",
        "unit": "minutes",
        "source": "GMAT State Report, densified ground track",
        "calculation": "95th percentile of the pooled per-cell time gaps, from core.constellation_analytics.compute_revisit_analytics()",
        "significance": "Characterises the long tail without being dominated by the single absolute worst case (Maximum Revisit Time) -- useful for setting a realistic worst-case SLA.",
    },
    {
        "key": "revisit_distribution",
        "name": "Revisit Time Frequency Distribution",
        "definition": "A histogram of every pass-to-pass gap pooled from all 180 sampled AOI grid points, grouped into 8 equal-width time bins from the shortest gap observed to the longest.",
        "unit": "count of intervals per bin",
        "source": "GMAT State Report, densified ground track",
        "calculation": "numpy.histogram(pooled gaps, bins=8), from core.constellation_analytics.compute_revisit_analytics()",
        "significance": "Where the Mean/Median/Best/Worst KPIs each collapse the whole distribution to one number, this chart shows its actual shape -- e.g. whether most of the AOI is revisited quickly with only a thin tail of slow cells, or whether long gaps are common. A tall left bar with a long low tail (the usual shape for a single Walker-Delta shell) means most locations are revisited quickly and only a few edge-of-swath cells wait much longer -- exactly the cells the Maximum/P95 KPIs are describing.",
    },
    {
        "key": "nominal_orbit_altitude",
        "name": "Nominal Orbit Altitude",
        "definition": "The constellation's design/configured circular orbit altitude -- a single fixed value, the same for every satellite regardless of where each one currently is in its orbit.",
        "unit": "km",
        "source": "Mission_Configuration.xlsx (Orbit table)",
        "calculation": "Read directly from the configuration file, not derived or propagated.",
        "significance": "The reference altitude the constellation is designed to fly at. Compare against Instantaneous Geodetic Altitude to see how far a satellite's real, propagated position deviates from this design value at any given moment.",
    },
    {
        "key": "instantaneous_geodetic_altitude",
        "name": "Instantaneous Geodetic Altitude",
        "definition": "A satellite's actual height above the reference ellipsoid at one specific moment in its GMAT-propagated orbit. Unlike the fixed Nominal Orbit Altitude, this value changes continuously as the satellite moves, because a real orbit is never a perfect circle.",
        "unit": "km",
        "source": "GMAT State Report (Satellite_State_History.xlsx, 'Altitude' column)",
        "calculation": "Read per timestep from the propagated state. Where a min/mean/max is shown, it is this same quantity aggregated over the analysis window or over the fleet.",
        "significance": "Shows the real, physical deviation from the nominal design altitude. A wide spread between min and max, or a mean that drifts from the Nominal Orbit Altitude, signals orbital decay or drift that would need a correction.",
    },
    {
        "key": "footprint_alignment",
        "name": "Footprint Alignment",
        "definition": "Whether the simulated observation and the real Earth reference image cover the exact same ground area, in the same orientation and scale.",
        "unit": "pass/fail",
        "source": "core.products.generate_product",
        "calculation": "Both images are rendered from one identical windowed read (same bbox, same output raster shape) of the real Sentinel-2 mosaic -- alignment is guaranteed by that construction, not independently measured or registered.",
        "significance": "Confirms there is no separate registration step that could silently misalign the two images -- they are geometrically the same frame by design.",
    },
    {
        "key": "land_cover_similarity",
        "name": "Land-Cover Similarity",
        "definition": "How closely the simulated product's land-cover mix (water / vegetation / bare / urban / cloud) matches the real reference scene's, after the same spectral-index classifier is applied to both.",
        "unit": "%",
        "source": "core.validation.compare_scenes, using core.classify.classify_scene on both images",
        "calculation": "100 - (sum of |reference% - simulated%| across classes) / 2. The simulated side is classified on DN rescaled to a comparable range, not on the raw reflectance the reference uses.",
        "significance": "A high value means the sensor simulation (blur, noise, atmosphere) preserved the scene's real land-cover mix; a lower value quantifies how much those effects shifted the apparent scene -- expected to some degree, since the whole point of the simulation is to model a real sensor's imperfections, not reproduce the reference pixel-for-pixel.",
    },
    {
        "key": "validation_confidence",
        "name": "Overall Validation Confidence",
        "definition": "A single disclosed indicator combining coordinate validity, footprint alignment, land-cover similarity and image quality into one number.",
        "unit": "0-100",
        "source": "core.validation.compare_scenes",
        "calculation": "Weighted mean of the four factors (20% coordinate validity, 20% footprint alignment, 30% land-cover similarity, 30% image quality), itemised the same way the Quality Score is.",
        "significance": "SIMULATED indicator, not a measured scientific result and not a statement about ASC_074's real-world imaging performance -- it summarises the checks already shown individually, for a quick read, not a new measurement.",
    },
    {
        "key": "solar_elevation",
        "name": "Sun Elevation",
        "definition": "The angle of the sun above the horizon at the observation's location and simulated capture time.",
        "unit": "degrees",
        "source": "core.solar.solar_position",
        "calculation": "Standard low-precision solar position formula (Cooper's equation for declination, longitude-based local solar time, then the elevation identity) from the capture timestamp and sub-satellite latitude/longitude. No equation-of-time or refraction correction, accurate to roughly +/-2 degrees.",
        "significance": "Characterises illumination conditions -- low or negative sun elevation means long shadows, a dim scene, or a night-side capture, none of which the sensor simulation currently adjusts pixel rendering for.",
    },
    {
        "key": "spectral_band_proxy",
        "name": "Spectral Band Proxy",
        "definition": "The center wavelength and bandwidth shown for each band (Red/Green/Blue/Near Infrared) are Sentinel-2's own published MSI specification, not a specification of ASC_074's own sensor.",
        "unit": "nm",
        "source": "core.spectral.SPECTRAL_BANDS",
        "calculation": "ASC_074's spectral response has never been specified in any mission file -- only the band names exist. The pipeline reads real Sentinel-2 L2A pixel data for each named band (Blue->B02, Green->B03, Red->B04, Near Infrared->B08), so Sentinel-2's real, published wavelength and bandwidth numbers are reported here as an ASSUMED proxy describing what data is actually feeding the pipeline.",
        "significance": "Makes explicit that using this data does not demonstrate ASC_074 has an identical spectral response to Sentinel-2 -- only that its simulated bands are currently modelled as if it did.",
    },
]

BY_KEY = {item["key"]: item for item in GLOSSARY}
